![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.10 Mathematical and Statistical methods

First we import numpy library:

In [1]:
import numpy as np

Here we create a two-dimensional array:

In [2]:
array1 = np.random.randn(4, 5)
array1

array([[-0.00320844,  0.07349777,  0.13016683,  2.31008908,  0.28560643],
       [ 0.12461897, -1.32824579,  1.89111807, -0.12169976,  0.7842233 ],
       [ 0.07253599,  2.01722233, -0.29318444,  0.50617902,  2.51987334],
       [-1.34638161,  0.8941427 , -0.67649225, -0.75862097,  0.66861239]])

We can calculate the mean of the array using the mean() function:

In [3]:
array1.mean()

0.3875026479745699

We can also calculate the mean using the numpy function np.mean():

In [4]:
np.mean(array1)

0.3875026479745699

Similarly, we can calculate the minimum, maximum, standard deviation and cumulative sum, like this:

In [5]:
array1.min()

-1.346381609978168

In [6]:
array1.max()

2.5198733420523496

In [7]:
array1.std()

1.0789344654834638

In [8]:
array1.cumsum()

array([-3.20843652e-03,  7.02893287e-02,  2.00456158e-01,  2.51054524e+00,
        2.79615167e+00,  2.92077064e+00,  1.59252484e+00,  3.48364292e+00,
        3.36194316e+00,  4.14616646e+00,  4.21870245e+00,  6.23592478e+00,
        5.94274034e+00,  6.44891935e+00,  8.96879270e+00,  7.62241109e+00,
        8.51655379e+00,  7.84006154e+00,  7.08144057e+00,  7.75005296e+00])

____________________________________________________________________________

### Here we practice two important functions, argmin() and argmax():

argmin() returns the index of the minumum value.

argmax() returns the index of the maximum value.

In [9]:
array2 = np.array([77, 46, 85, 22, 28, 89, 63, 43,  4, 76])
array2

array([77, 46, 85, 22, 28, 89, 63, 43,  4, 76])

In [10]:
array2.min()

4

In [11]:
array2.argmin()

8

In [12]:
array2.argmax()

5

Lets now create a two dimensional array:

In [13]:
array1

array([[-0.00320844,  0.07349777,  0.13016683,  2.31008908,  0.28560643],
       [ 0.12461897, -1.32824579,  1.89111807, -0.12169976,  0.7842233 ],
       [ 0.07253599,  2.01722233, -0.29318444,  0.50617902,  2.51987334],
       [-1.34638161,  0.8941427 , -0.67649225, -0.75862097,  0.66861239]])

We can create statistics for rows or columns separately, using the argument axis = 0 or axis =1:

In [14]:
array1.sum(axis = 0)

array([-1.15243509,  1.65661701,  1.05160821,  1.93594737,  4.25831547])

In [15]:
array1.sum(axis = 1)

array([ 2.79615167,  1.35001479,  4.82262624, -1.21873974])

We can also use statistics for boolean values, like this:

In [16]:
array3 = np.array([True, False, False, True, True])
array3

array([ True, False, False,  True,  True])

In [17]:
array3.sum()

3

In [18]:
array3.any()

True

In [19]:
array3.all()

False

In [20]:
array4= np.array([True, True, True, True])
array4

array([ True,  True,  True,  True])

In [21]:
array4.all()

True

***

<h1 align="center">Thank You</h1> 

***