![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.11 Sorting Arrays

First we import numpy library:

In [1]:
import numpy as np

Here we create a numpy array using the numpy function **random.randn**:

In [2]:
array1 = np.random.randn(5)
array1

array([ 0.70738724, -0.80355015,  0.79567203, -0.99274388,  0.75563639])

We can sort the array using the function **sort()**

In [3]:
array1.sort()
array1

array([-0.99274388, -0.80355015,  0.70738724,  0.75563639,  0.79567203])

We can also use the function **np.sort()**:

In [4]:
np.sort(array1)

array([-0.99274388, -0.80355015,  0.70738724,  0.75563639,  0.79567203])

To sort the array in descending order we use this indexing **[ : : -1 ]**:

In [5]:
np.sort(array1)[::-1]

array([ 0.79567203,  0.75563639,  0.70738724, -0.80355015, -0.99274388])

Lets now create a two-dimensional array:

In [6]:
array2 = np.random.randn(4,5)
array2

array([[ 0.9179914 ,  0.07135296,  0.65306944,  1.16284718, -0.30615008],
       [-0.47692633,  0.21942212,  0.06191353,  0.41440359, -1.36193126],
       [ 1.41535478, -0.2282855 , -0.42808822, -0.83884842, -0.10822217],
       [ 1.13436909,  2.08342833, -0.04935094, -0.36525635, -1.38775066]])

To sort within columns:

In [7]:
array2.sort(1)
array2

array([[-0.30615008,  0.07135296,  0.65306944,  0.9179914 ,  1.16284718],
       [-1.36193126, -0.47692633,  0.06191353,  0.21942212,  0.41440359],
       [-0.83884842, -0.42808822, -0.2282855 , -0.10822217,  1.41535478],
       [-1.38775066, -0.36525635, -0.04935094,  1.13436909,  2.08342833]])

To sort within rows:

In [8]:
array2.sort(0)
array2

array([[-1.38775066, -0.47692633, -0.2282855 , -0.10822217,  0.41440359],
       [-1.36193126, -0.42808822, -0.04935094,  0.21942212,  1.16284718],
       [-0.83884842, -0.36525635,  0.06191353,  0.9179914 ,  1.41535478],
       [-0.30615008,  0.07135296,  0.65306944,  1.13436909,  2.08342833]])

We can use a numpy function called **np.unique()** to return a sorted unique elements:

In [9]:
array3 = np.array(['Harry', 'Jake', 'Harry', 'George', 'Jake', 'Harry', 'James', 'Jake', 'Jake', 'Harry'])
array3

array(['Harry', 'Jake', 'Harry', 'George', 'Jake', 'Harry', 'James',
       'Jake', 'Jake', 'Harry'], dtype='<U6')

In [10]:
np.unique(array3)

array(['George', 'Harry', 'Jake', 'James'], dtype='<U6')

***

<h1 align="center">Thank You</h1> 

***