![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.12 File Input and Output with Arrays

First we import numpy library:

In [1]:
import numpy as np

Lets now create a numpy array using the function **np.arange()**:

In [2]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can save this array using the function **np.save()**:

In [3]:
np.save('my_array', array1)

We can load the saved array using the function **np.load()**:

In [4]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can assign a new variable for the loaded array like this:

In [5]:
array2 = np.load('my_array.npy')
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can save multiple arrays using the function **np.savez()**:

In [6]:
np.savez('multiple_arrays.npz', a1 =array1, a2 = array2)

The multi-array file can be loaded normally using the function **np.load()**:

In [7]:
arrays = np.load('multiple_arrays.npz')

We use the keys ( a1, a2 ) to access the loaded arrays:

In [8]:
arrays['a1']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arrays['a2']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***

<h1 align="center">Thank You</h1> 

***