![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.2 Creating Ndarrays

First we import numpy library

In [1]:
import numpy as np

We create a numpy array using the function random.randn() from numpy library:

In [2]:
array = np.random.randn(2,3)

Lets display the array

In [3]:
array

array([[ 0.41679232, -0.10814479, -0.50131846],
       [-0.24938131, -0.78549902, -0.90698918]])

To check the dimension of the array we use the attribute .ndim

In [4]:
array.ndim

2

To check the shape of this array, we use the attribute .shape

In [5]:
array.shape

(2, 3)

To check the data type of the array we use the attribute dtype:

In [6]:
array.dtype

dtype('float64')

Here we create a list:

In [7]:
list1 = [3,1,5,6,9,3]

We can convert this list into numpy array using the numpy function array():

In [8]:
array1 = np.array(list1)

Lets display the array:

In [9]:
array1

array([3, 1, 5, 6, 9, 3])

Lets check the type of this variable using th type() function:

In [10]:
type(array1)

numpy.ndarray

Lets check the dimension using th attribute ndim:

In [11]:
array1.ndim

1

lets check the shape using the attribute shape

In [12]:
array1.shape

(6,)

Here we create a nested list:

In [13]:
list2 = [[1,2,3], [4,5,6]]

We can convert this list into a numpy array using the numpy function array()

In [14]:
array2 = np.array(list2)

Lets display this array:

In [15]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

Lets check its dimension:

In [16]:
array2.ndim

2

Lets check its shape:

In [17]:
array2.shape

(2, 3)

Here we create a list with mixed data types ( integers and floats numbers):

In [18]:
list3 = [1, 1.5, 1., 6]

Lets convert this list into a numpy array to examine the resulted data type:

In [19]:
array3 = np.array(list3)
array3

array([1. , 1.5, 1. , 6. ])

Lets check data types

In [20]:
array3.dtype

dtype('float64')

We can create a numpy array with certain size filled with zeros like this: 

In [21]:
array4 = np.zeros(10)
array4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

We can create two dimensional numpy array filled with ones like this:

In [22]:
array6 = np.ones((3,4))
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

***

<h1 align="center">Thank You</h1> 

***