![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.3 Data Types For Ndarrays

First we import numpy library:

In [1]:
import numpy as np

Here we create a list then we convert it into a numpy array:

In [2]:
list1 = [1,2,3,4,5]
array1 = np.array(list1)
array1

array([1, 2, 3, 4, 5])

We check the data type of this array like this:

In [3]:
array1.dtype

dtype('int32')

We can assign a new data type to an existing array like this:

In [4]:
array2 = np.array(list1, dtype = 'int16')

Lets check now the data type

In [5]:
array2.dtype

dtype('int16')

We can create a numpy array with pre-specified data type, which is here float numbers:

In [6]:
array_float = array2.astype(np.float64)
array_float

array([1., 2., 3., 4., 5.])

Lets create a list of different age values, notice that the values are not numerical.

In [7]:
list2 = ['19','24','34','14','56']

Lets convert this list into a numpy array:

In [8]:
array_age = np.array(list2)

Lets check the data type of this array:

In [9]:
array_age.dtype

dtype('<U2')

If we try an arithmetic operation with this array we get an error, because it is not numerical:

In [10]:
array_age -5

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U3'), dtype('<U3')) -> dtype('<U3')

We can change the data type into numerical like this:

In [11]:
array_age = array_age.astype(np.int16)

Now if we try an arithmetic operation, it works without any problem:

In [12]:
array_age - 5

array([14, 19, 29,  9, 51], dtype=int16)

***

<h1 align="center">Thank You</h1> 

***