![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.4 Arithmetic With NumPy Arrays 

First we import Numpy library:

In [1]:
import numpy as np

We can create two dimensional numpy array like this:

In [2]:
array = np.array([[1,2,3], [4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

We can do element-wise multiplication of this array by itself, like this:

In [3]:
array * array

array([[ 1,  4,  9],
       [16, 25, 36]])

We can do element-wise subtraction of this array from itself, like this:

In [4]:
array - array

array([[0, 0, 0],
       [0, 0, 0]])

We can do element-wise multiplication of this array by number 4, like this:

In [5]:
array * 4

array([[ 4,  8, 12],
       [16, 20, 24]])

We can do element-wise division of this array by number 2, like this:

In [6]:
array /2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

We can raise each element to the power of two, like this:

In [7]:
array ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

We can do boolean operation like this:

In [8]:
array > 4

array([[False, False, False],
       [False,  True,  True]])

***

<h1 align="center">Thank You</h1> 

***