![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.5 Indexing And Slicing-part One

First we import numpy library like this:

In [1]:
import numpy as np

We create a one dimensional numpy array using arange() function like this: 

In [2]:
array = np.arange(2,20,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

To slice the fifth element:

In [3]:
array[4]

10

To slice a range of elements from the third to the eighth element:

In [4]:
array[2:8]

array([ 6,  8, 10, 12, 14, 16])

To slice for the begining, we leave the start before the colon empty:

In [5]:
array[:6]

array([ 2,  4,  6,  8, 10, 12])

To slice to the end, we leave the end after the colon empty:

In [6]:
array[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

To slice the whole array we use only the colon:

In [7]:
array[:]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

To show that the slice is a mirror, not a copy, lets first assign the slice to a new array like this:

In [8]:
slice1 = array[2:6]
slice1

array([ 6,  8, 10, 12])

Now we change the first element to number 99:

In [9]:
slice1[0] = 99
slice1

array([99,  8, 10, 12])

Lets display the original array, to see if it is changed when the slice is changed.

In [10]:
array

array([ 2,  4, 99,  8, 10, 12, 14, 16, 18])

To make the slice a copy not a mirror we use the function copy()

In [11]:
slice2= array[2:5].copy()
slice2

array([99,  8, 10])

***

<h1 align="center">Thank You</h1> 

***