![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.6 Indexing And Slicing-part Two

First we import numpy library:

In [1]:
import numpy as np

Here we creat 4 by 3 array using a nested list:

In [2]:
array2d = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
array2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

To slice a two-dimentional array, we use two colons, one for rows and one for columns:

In [3]:
array2d[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

If we use one colon, python recognize it for the rows:

In [4]:
array2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

Here we use a bare colon to select all rows:

In [5]:
array2d[:,1]

array([ 2,  5,  8, 11])

We can select a range of rows and a range of columns like this:

In [6]:
array2d[1:3, 1:4]

array([[5, 6],
       [8, 9]])

Without colons, a single row or a single colum can be selected like this:

In [7]:
array2d[2,1]

8

***

<h1 align="center">Thank You</h1> 

***