![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.7 Boolean Indexing

First we import numpy library:

In [1]:
import numpy as np

Here we creat an array consistes of letters using the array() function:

In [2]:
array1 = np.array(['a', 'b', 'c', 'a', 'd', 'b', 'a'])
array1

array(['a', 'b', 'c', 'a', 'd', 'b', 'a'], dtype='<U1')

Here we creat another array:

In [3]:
array2 =  np.array([22,45,22,61,19,23,31])
array2

array([22, 45, 22, 61, 19, 23, 31])

We can use boolean indexing to use a subset of an array based on a condition for another array, like this:

In [4]:
array2[array1 == 'a']

array([22, 61, 31])

The boolean expression returns Boolean values, like this:

In [5]:
array1 == 'a'

array([ True, False, False,  True, False, False,  True])

Lets create a two-dimensional array using the function random.randn() like this

In [6]:
array3 = np.random.randn(7,2)
array3

array([[-0.90586175,  0.7326374 ],
       [ 1.02160145,  2.72134477],
       [ 1.22924526,  0.55413214],
       [-0.32314042, -0.10557165],
       [-0.6531677 ,  0.04914965],
       [-0.78484181, -1.35117332],
       [-0.63059521,  0.23137827]])

We can also use boolean indexing for two-dimentional array, like this example:

In [7]:
array3[array1 == 'a']

array([[-0.90586175,  0.7326374 ],
       [-0.32314042, -0.10557165],
       [-0.63059521,  0.23137827]])

In this example we use a nested list to create a two dimensional array of 10 rows by 2 columns

In [8]:
array4 = np.array([[1,23], [4,43], [1, 17],[3,53], [5,23], [1, 42],[3,15], [1,34], [4, 41],[2, 23]])
array4

array([[ 1, 23],
       [ 4, 43],
       [ 1, 17],
       [ 3, 53],
       [ 5, 23],
       [ 1, 42],
       [ 3, 15],
       [ 1, 34],
       [ 4, 41],
       [ 2, 23]])

Lets check the shape of this array using the shape attribute

In [9]:
array4.shape

(10, 2)

We can boolean indexing for an array based on a column in the same array, like this example, where we sliced the array based on the values in the first column:

In [10]:
array4[array4[:,0] == 1]

array([[ 1, 23],
       [ 1, 17],
       [ 1, 42],
       [ 1, 34]])

***

<h1 align="center">Thank You</h1> 

***