![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.8 Fancy Indexing

First we import numpy library:

In [1]:
import numpy as np

Here we create a numpy array using the numpy function random.randint 

In [2]:
array1 = np.random.randint(50, size= 10)
array1

array([34, 46, 11, 33, 30, 23, 30, 41, 15,  8])

To Use Fancy indexing, we can create any index to be used to slice the data, like this one

In [3]:
ind = [1,3,5,7]

Here we used the index that we created int the last code line to select a subset of the array1

In [4]:
array1[ind]

array([46, 33, 23, 41])

We can create an index with different shapes, here we create a two-dimentional index:

In [5]:
ind2 = np.array([[1,3], [5,7]])
ind2

array([[1, 3],
       [5, 7]])

We can use the created two-dimentional inde to slice array1, like this:

In [6]:
array1[ind2]

array([[46, 33],
       [23, 41]])

Now lets create a two-dimensional array:

In [7]:
array2 = np.random.randint(100, size=(3,4))
array2

array([[58, 95, 11, 61],
       [85, 89, 26, 94],
       [27, 68, 25, 72]])

To slice two-dimensional array, We create an index that contains two sets, one for rows and one for columns:

In [8]:
ind = ((0,1,2),(3,2,3))
ind

((0, 1, 2), (3, 2, 3))

In [9]:
array2[ind]

array([61, 26, 72])

We can also create two separate indexes, one for rows and one for columns: 

In [10]:
row = [0,1,2]
column = [3,2,3]

In [11]:
array2[row,column]

array([61, 26, 72])

***

<h1 align="center">Thank You</h1> 

***