![title](img/cover4.png)

<center><em>Copyright! This material is protected, please do not copy or distribute.    by:Taher Assaf</em></center>

***
<h1 align="center">Udemy course : Python Bootcamp for Data Science 2021 Numpy Pandas & Seaborn</h1> 

***

## 6.9 Transposing Arrays

First we import numpy library:

In [1]:
import numpy as np

Here we creat a two-dimensional numpy array:

In [2]:
array1  = np.random.randint(20, size= (3,4))
array1

array([[14,  6, 17,  2],
       [13,  9, 17, 16],
       [15,  9,  6,  5]])

We can transpose the array using the function transpose():

In [3]:
array1.transpose()

array([[14, 13, 15],
       [ 6,  9,  9],
       [17, 17,  6],
       [ 2, 16,  5]])

We can also transpose the array using the attribute .T:

In [4]:
array1.T

array([[14, 13, 15],
       [ 6,  9,  9],
       [17, 17,  6],
       [ 2, 16,  5]])

Lets create a one-dimensional array:

In [5]:
array2 = np.array([1,2,3,4,5,6])
array2

array([1, 2, 3, 4, 5, 6])

If we try to transpose a one dimensional array, it will be the same:

In [6]:
array2.T

array([1, 2, 3, 4, 5, 6])

***

<h1 align="center">Thank You</h1> 

***